# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_pica4r_wrappers", use_symbols = TRUE, package_name = "pica4r")

#' @docType package
#' @usage NULL
#' @useDynLib pica4r, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
pica_select <- function(filename, selectors, header) .Call(wrap__pica_select, filename, selectors, header)

