[package]
name = 'pica4r'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
# extendr-api = '*'
extendr-api = { git = 'https://github.com/extendr/extendr' }
pica = { path = "../../../" }
libR-sys = "0.2"
csv = "1.1"
