[workspace]
default-members = ["crates/pica-cli"]
members = ["crates/pica-cli"]
resolver = "3"

[workspace.package]
version = "1.4.0"
authors = ["Nico Wagner <n.wagner@dnb.de>"]
license = "EUPL-1.2"
rust-version = "1.95"
edition = "2024"

[package]
name = "pica-record"
authors.workspace = true
categories = ["parser-implementations"]
description = "A toolkit for processing PICA+ records."
edition.workspace = true
keywords = ["pica+", "code4lib"]
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
compat = []
nightly = []
performant = []
serde = ["dep:serde", "bstr/serde"]
unstable = []

[dependencies]
bstr = { version = "1.13.1" }
flate2 = { version = "1.1.10" }
regex = { version = "1.13.1" }
serde = { version = "1.0.229", optional = true, features = ["derive"] }
sha2 = { version = "0.11.0" }
smallvec = { version = "1.15.2" }
strsim = { version = "0.11.1" }
hashbrown = { version = "0.17.1" }
thiserror = { version = "2.0.20" }
winnow = { version = "1.0.4" }

[dev-dependencies]
anyhow = { version = "1.0.104" }
pica-record = { path = "./", features = ["serde"] }
quickcheck = { version = "1.1.0" }
quickcheck_macros = { version = "1.2.0" }
serde_test = { version = "1.0.177" }
tempfile = { version = "3.27.0" }

[lib]
path = "src/lib.rs"

[[test]]
path = "tests/lib.rs"
name = "integration"

[profile.release]
lto = "fat"
panic = "abort"
debug = "none"
codegen-units = 1
opt-level = 3
strip = true

[profile.dev]
debug = 0
