project:
  type: book


lang: de

book:
  title: pica-rs
  author:
    - name: Nico Wagner
      orcid: 0000-0002-2033-1806
      affiliations:
        - name: Deutsche Nationalbibliothek
          url: https://www.dnb.de/
  date: "11/6/2024"
  chapters:
    - index.qmd
    - part: "Erste Schritte"
      chapters:
        - install.qmd
    - part: "Kommandos"
      chapters:
        - commands/concat.qmd
        - commands/config.qmd
        - commands/invalid.qmd
    # - summary.qmd
    # - references.qmd
  sidebar:
    logo: assets/img/logo.png

bibliography: references.bib

format:
  html:
    theme: flatly
    css: assets/css/style.css
    fontsize: 0.9em
    fontcolor: "#333"
    toc: false
