project:
  type: book


lang: de

book:
  title: pica-rs
  author:
    - name: Nico Wagner
      orcid: 0000-0002-2033-1806
      affiliations:
        - name: Deutsche Nationalbibliothek
          url: https://www.dnb.de/
    - name: Maximilian Kähler
      orcid: 0000-0003-4695-0565
      affiliations:
        - name: Deutsche Nationalbibliothek
          url: https://www.dnb.de/
  date: "11/6/2024"
  chapters:
    - index.qmd
    - part: "Erste Schritte"
      chapters:
        - install.qmd
    - part: "Tutorials"
      chapters:
        - tutorials/beginner.qmd
        - tutorials/rmarkdown.qmd
    - part: "Kommandos"
      chapters:
        - commands/completions.qmd
        - commands/concat.qmd
        - commands/config.qmd
        - commands/convert.qmd
        - commands/count.qmd
        - commands/explode.qmd
        - commands/filter.qmd
        - commands/frequency.qmd
        - commands/hash.qmd
        - commands/invalid.qmd
        - commands/partition.qmd
        - commands/print.qmd
        - commands/sample.qmd
        - commands/select.qmd
        - commands/slice.qmd
        - commands/split.qmd
    # - summary.qmd
    # - references.qmd
  sidebar:
    logo: assets/img/logo.png

bibliography: references.bib

format:
  html:
    theme: flatly
    css: assets/css/style.css
    fontsize: 0.9em
    fontcolor: "#333"
    toc: false
