[book]
authors = ["Nico Wagner"]
language = "de"
multilingual = false
title = "pica-rs"
src = "src"

[build]
create-missing = false

[rust]
edition = "2021"

[output.html.search]
limit-results = 15

[preprocessor.keeper]
command = "mdbook-keeper"
manifest_dir = "docs/book/deps"
externs = ["pica_record"]
