[book]
authors = ["Nico Wagner"]
language = "de"
multilingual = false
title = "pica-rs"
src = "src"

[build]
create-missing = false

[rust]
edition = "2021"

[output.html]
additional-css = ["custom.css"]

[output.html.search]
limit-results = 15
