baseURL = "https://deutsche-nationalbibliothek.github.io/pica-rs/book/"
languageCode = "de-DE"
title = "pica-rs"

enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[menu]
[[menu.after]]
name = "GitHub"
url = "https://github.com/deutsche-nationalbibliothek/pica-rs/"
weight = 10

[[menu.after]]
name = "Rust API"
url = "https://deutsche-nationalbibliothek.github.io/pica-rs/api/doc/pica_record/index.html"
weight = 20

[params]
BookComments = false
BookSearch = false
BookToc = false
