### Filter-Optionen

`-s`, `--skip-invalid`
: Überspringt jene Zeilen aus der Eingabe, die nicht dekodiert werden
konnten.

`-l <number>`, `--limit <number>`
: Eingrenzung der Ausgabe auf die ersten _n_ Datensätze.

`-i`, `--ignore-case`
: Groß- und Kleinschreibung wird bei Vergleichen ignoriert.

`--strsim-threshold <value>`
: Festlegen des Schwellenwerts beim Ähnlichkeitsvergleich von
Zeichenketten mittels `=*`.

`-A <file>`, `--allow-list` `<file>`
: Es werden alle Datensätze ignoriert, die nicht explizit in der
Positivliste auftauchen. Werden mehrere Positivlisten angegeben, wird
die Mengenvereinigung aus allen Listen gebildet.

`-D <file>`, `--deny-list` `<file>`
: Es werden alle Datensätze ignoriert, die in der Negativliste
auftauchen. Werden mehrere Negativlisten angegeben, wird die
Mengenvereinigung aus allen Listen gebildet.

`--filter-set-column <column>`
: Legt den Spaltennamen fest, der die Referenzwerte einer Allow- bzw.
Deny-Liste enthält. Wird die Option nicht angegeben, werden die Werte
aus der Spalte `ppn` bzw. `idn` ausgelesen. Die `idn`-Spalte wird nur
versucht zu lesen, wenn keine `ppn`-Spalte vorhanden ist.

`--filter-set-path <path>`
: Ein Pfadausdruck, der zur Ermittlung der Vergleichswerte genutzt wird.
Ist die Option nicht angegeben, wird von einem Vergleich mit der PPN im
Feld `003@.0` eines Datensatzes ausgegen.

`--where <expr>`
: Angabe eines Filters, um Datensätze aus der Eingabe auszuwählen.

`--and <expr>`
: Hinzufügen eines zusätzlichen Filters mittels der booleschen
`&&`-Verknüpfung. Der ursprüngliche Filterausdruck `<filter>` wird zum
Ausdruck `<filter> && <expr>`.

`--or <expr>`
: Hinzufügen eines zusätzlichen Filters mittels der booleschen
`||`-Verknüpfung. Der ursprüngliche Filterausdruck `<filter>` wird zum
Ausdruck `<filter> || <expr>`.

`--not <expr>`
: Hinzufügen eines zusätzlichen Filters. Der ursprüngliche
Filterausdruck `<filter>` wird zum Ausdruck `<filter> && !(<expr>)`.

