id = "AEN"

# Check soll nur für Webformular-Ablieferung gelten.
scope = "002@.0 =^ 'O' && 002M.b == 'Webformular'"
 
[rule.AEN000201]
description = """
Test, ob in Olfo-Datensätzen die Zählung der Einheit eine vierstellige 
Zahl enthält.
"""
severity = "info"
check.lint = "filter"
check.filter = """
   002@.0 == 'Olfo' 
&& 002M.b == 'Webformular' 
&& 031A.d =~ '[0-9]{4}'
"""
 
[rule.AEN000202]
description = """
Test, ob Oaf-Datensätze mit dem Titel Jahresbericht vorhanden sind. 

Hintergrund: Dieser Titel weist auf eine Zeitschrift hin, die 
Ablieferung geschah aber monografisch als Oaf.
"""
severity = "info"
check.lint = "filter"
check.filter = "002@.0 == 'Oaf' && 021A.a =~ 'Jahresbericht'"
 
[rule.AEN000203]
description = """
Test, ob Oaf-Datensätze mit dem Titel Jahresbericht vorhanden sind - 
bezogen auf Titel und Gesamttitel. 

Hintergrund: Dieser Titel weist auf eine Zeitschrift hin, die 
Ablieferung geschah aber monografisch als Oaf.
"""
severity = "info"
check.lint = "filter"
check.filter = """
   002@.0 == 'Oaf' 
&& 021A.a =~ 'Jahresbericht' 
&& 036F.a =~ 'Jahresbericht'
"""
