id = "DNB"

[rule.DNB000001]
description = "Test, ob die PPN/IDN im Feld `003@.0` ungültig ist."
check = { lint = "checksum", path = "003@.0" }

[rule.DNB000002]
description = "Test, ob der Datensatz ungültige UTF-8 Sequenzen enthält."
check.lint = "unicode"

[rule.DNB000003]
description = "Test, ob das Feld `003@` und/oder das Unterfeld `0` mehrfach vorkommt."
check = { lint = "filter", filter = "#003@ > 1 || 003@{ #0 > 1 }" }

[rule.DNB000004]
description = "Test, ob das Feld `002@` und/oder das Unterfeld `0` mehrfach vorkommt."
check = { lint = "filter", filter = "#002@ > 1 || 002@{ #0 > 1 }" }

[rule.DNB000005]
description = "Test, ob das Feld `002@.9` eine gültige Satzart enthält"
check = { lint = "filter", filter = "002@.0 !~ '^([A-Za-z]{2,4}|T[bfgpsu][1-6z])$'" }

[rule.DNB000006]
description = "Test, ob das Feld `001A.a` ein ungültiges Datum enthält."
check = { lint = "date", path = "001A.0", format = "%d-%m-%y", offset = 5 }
