id = "GND"
scope = "002@.0 =~ '^T[bfgnpsu].*'"

[rule.GND000001]
check = { lint = "filter", filter = "002@.0 !~ '^T[bfgnpsu][1-7z]e?$'" }

[rule.GND000002]
description = "Test, ob im Feld `003U $a` eine gültige IRI steht."
check = { lint = "iri", path = "003U.a" }

[rule.GND000003]
description = """
Test, ob eine gülige Änderungscodierung im Feld `008@ $a` steht.
"""
check.lint = "filter"
check.filter = "008@.a not in ['d', 'g', 'p', 's', 'u', 'zd', 'zu']"

# Teilbestandskennzeichen
[rule.GND000004]
description = """
Test, ob im Feld `008A $a` ein gültiges Teilbestandskennzeichen steht.
"""
check.lint = "filter"
check.filter = """008A.a not in [
    'a', 'd', 'e', 'f', 'g', 'h', 'l', 
    'm', 'n', 'o', 'p', 's', 't', 'z'
]
"""

[rule.GND000005]
description = """
Test, ob im Feld `008B $a` ein gültiges Nutzungskennzeichen steht.
"""
check.lint = "filter"
check.filter = """
    008B.a not in ['e', 'h', 'k', 'm', 'o', 'r', 'v', 'w', 'z']
"""

[rule.GND000006]
check = { lint = "iso639", path = "02[29]@.L" }

[rule.GND000007]
check = { lint = "iso639", path = "030@.L" }

[rule.GND000008]
check = { lint = "iso639", path = "041@.L" }

[rule.GND000009]
check = { lint = "iso639", path = "065@.L" }

[rule.GND000010]
description = """
Dieser Check überprüft, ob in Tb-Sätzen, bei denen im Feld 
"Bevorzugter Name" das Unterfeld $g mit "Musikgruppe" belegt ist, 
die Verknüpfung zum Sachbegriff "Musikgruppe" fehlt.
"""
check.lint = "filter"
check.filter = """
   002@.0 in ['Tb1', 'Tb3'] 
&& 029A.g =^ 'Musikgruppe' 
&& #041R{9 == '04170827X'} == 0
"""

# [rule.GND000011]
# check = { lint = "gnd-subject-category", path = "042A.a" }

[rule.GND000012]
description = """
Test, ob bei Personen eine gültige Geschlechtsangabe vorliegt.
"""
check.lint = "filter"
check.filter = "002@.0 =^ 'Tp' && 032T.a not in ['m', 'f']"


