id = "ME"

# Prüfung auf Satzart (002@), AKZ-Vergabe (209C), Bearbeitung durch
# ME-L (047A).
scope = """
    002@.0 in ['Aaa', 'Aam', 'Aac', 'Gamm', 'Gaam', 'Maam', 'Mamm', 'Sac', 'Kac']
 && 209C/01.a? && 047A.S == 'ME-L'
"""

[rule.ME000101]
description = "Test, ob der Datensatz einen Reihencode enthält."
severity = "error"
check = { lint = "filter", filter = "!017A.a?" }

[rule.ME000102]
description = "Test, ob der Datensatz ein Erscheinungsjahr enthält."
severity = "error"
check = { lint = "filter", filter = "!011@.a?" }

[rule.ME000103]
description = "Test, ob der Datensatz einen Sprachencode enthält."
severity = "error"
check = { lint = "filter", filter = "!010@.a?" }

[rule.ME000104]
description = """Test, ob der Datensatz einen nach ISO 639-2/B gültigen
Sprachencode enthält.
"""
severity = "error"
check = { lint = "iso639", path = "010@.a" }

[rule.ME000105]
description = "Test, ob der Datensatz einen Ländercode enthält."
severity = "error"
check = { lint = "filter", filter = "!019@.a?" }

[rule.ME000106]
description = "Test, ob der Datensatz eine ISBN/Einbandart enthält."
severity = "error"
check = { lint = "filter", filter = "!004A.0?" }

[rule.ME000107]
description = "Test, ob der Datensatz einen Haupttitel enthält."
severity = "error"
check = { lint = "filter", filter = "!021A.a?" }

[rule.ME000108]
description = """
Test, ob der Datensatz einen Erscheinungsort/Verlag enthält.
"""
severity = "error"
check = { lint = "filter", filter = "!033A.n?" }
