organizational-unit = "GND"
name = "GND"

scope = "002@.0 =~ '^T[bfgnpsu].*'"

#
# Gruppe "000" - Allgemeine Felder
#

[rule.GND-000-001]
description = "Findet ungülige Statzarten im Feld `003@ $0`."
lint = { type = "filter", filter = "002@.0 !~ '^T[bfgnpsu][1-7z]e?$'" }

[rule.GND-000-002]
description = "Findet ungülige IRIs im Feld `003U $a`."
lint = { type = "iri", path = "003U.a" }

[rule.GND-000-003]
description = "Findet ungülige Änderungscodierung im Feld `008@ $a`."
lint = { type = "filter", filter = "008@.a not in ['d', 'g', 'p', 's', 'u', 'zd', 'zu']" }

[rule.GND-000-004]
description = "Findet ungültige Teilbestandskennzeichen im Feld `008A $a`."
lint.type = "filter"
lint.filter = "008A.a not in ['a', 'd', 'e', 'f', 'g', 'h', 'l', 'm', 'n', 'o', 'p', 's', 't', 'z']"

[rule.GND-000-005]
description = "Findet ungültige Nutzungskennzeichen im Feld `008B $a`."
lint.type = "filter"
lint.filter = "008B.a not in ['e', 'h', 'k', 'm', 'o', 'r', 'v', 'w', 'z']"

#
# Gruppe "001" - Personen (Tp)
#

[rule.GND-001-001]
description ="Findet Tp-Sätze, ohne bevorzugten Namen"
lint.type = "filter"
lint.filter = "002@.0 =^ 'Tp' && !028A?"

[rule.GND-001-002]
description ="Findet Tp-Sätze, mit wiedrholtem Feld `028A`"
lint.type = "filter"
lint.filter = "002@.0 =^ 'Tp' && #028A > 1"

[rule.GND-001-003]
description ="Findet Datensätze, mit unzulässiger Verwendung von `028A`."
lint.type = "filter"
lint.filter = "028A? && 002@{ 0 =~ '^Tp[1-6z]e$' || 0 !~ '^Tp' }"

[rule.GND-001-004]
description = "Findet Tp-Sätze mit ungültige Geschlechtsangabe."
lint = { type = "filter", filter = "002@.0 =^ 'Tp' && 032T.a not in ['m', 'f']" }

[rule.GND-001-005]
description = "Findet Tp-Sätze mit fehlender Code-Angabe in Feld 028R $4."
lint = { type = "filter", filter = "002@.0 =^ 'Tp' && 028R{ !4? }" }

[rule.GND-001-006]
description = "Findet Tp-Sätze mit ungültiger Code-Angabe in Feld 028R $4."
lint = { type = "filter", filter = "002@.0 =^ 'Tp' && 028R.4 not in ['beza', 'bezb', 'bezf', 'korr', 'mitg', 'nawi', 'obpa', 'pseu', 'rela', 'them', 'vbal']" }

[rule.GND-001-007]
description = "Findet Tp-Sätze mit fehlerhafter Referenz im Feld `028R.9`."
lint = { type = "ref-check", src = "028R.9", dst = "003@.0" }

#
# Gruppe "002" - Körperschaften (Tb)
#

[rule.GND-002-001]
description = "Findet ungültige Sprachencodes im Feld `029@ $L`"
lint = { type = "iso639", path = "029@.L" }

[rule.GND-002-002]
description = """
Dieser Check überprüft, ob in Tb-Sätzen, bei denen im Feld 
"Bevorzugter Name" das Unterfeld $g mit "Musikgruppe" belegt ist, 
die Verknüpfung zum Sachbegriff "Musikgruppe" fehlt.
"""
lint.type = "filter"
lint.filter = "002@.0 in ['Tb1', 'Tb3'] && 029A.g =^ 'Musikgruppe' && #041R{9 == '04170827X'} == 0"


#
# Gruppe "003" - Konferenzen (Tf)
#

[rule.GND-003-001]
description = "Findet ungültige Sprachencodes im Feld `030@ $L`"
lint = { type = "iso639", path = "030@.L" }

#
# Gruppe "004" - Geografikum (Tg)
#

[rule.GND-004-001]
description = "Findet ungültige Sprachencodes im Feld `065@ $L`"
lint = { type = "iso639", path = "065@.L" }

#
# Gruppe "005" - Sachbegriff (Ts)
#

[rule.GND-005-001]
description = "Findet ungültige Sprachencodes im Feld `041@ $L`"
lint = { type = "iso639", path = "041@.L" }

#
# Gruppe "006" - Werk (Tu)
#

[rule.GND-006-001]
description = "Findet ungültige Sprachencodes im Feld `022@ $L`"
lint = { type = "iso639", path = "022@.L" }

[rule.GND-006-002]
description = "Findet ungültige Angaben zum Inhaltstyp."
lint.type = "filter"
lint.filter = "002@.0 =^ 'Tu' && 032L.b in ['prm', 'ntv', 'cod', 'cop', 'tdf', 'tdm', 'snd', 'spw', 'crf', 'crn', 'crd', 'crm', 'cri', 'crt', 'ntm', 'tcn', 'tcf', 'tcm', 'tct', 'tci', 'txt', 'sti', 'tdi', 'xxx', 'zzz']"
