# check {.unnumbered}

::: {.callout-warning}
Das Kommando `check` ist eine `unstable`-Funktion, die sich noch in der
Entwicklung befindet und noch nicht in den Releases enthalten ist. Das
Kommando kann durch Aktivierung der `unstable`-Funktion beim Bauen aus
den Quellen aktiviert werden.
:::

Das `check`-Kommando erlaubt es, Datensätze auf Konformität mit einem
Regelwerk zu überprüfen. In einer (oder mehreren) Konfigurationsdateien
können Regeln hinterlegt werden, gegen die jeder Datensatz überprüft
wird. Trifft eine Regel zu, wird diese Regelverletzung unter Angabe
der PPN (Feld `003@ $0`) des Datensatzes und der ID der Regel in eine
Ausgabedatei geschrieben. Die ID einer Regel kann von den Nutzenden
frei gewählt werden.

Befinden sich die spezifizierten Regeln in der Datei `rules.toml`, kann
mit dem folgenden Befehl die Datei `DUMP.dat.gz` gegen das Regelwerk
überprüft werden. Die Ausgabe erfolgt im CSV-Format in die Ausgabedatei
`out.csv`:

```{.bash}
$ pica check -R rules.toml DUMP.dat.gz -o out.csv
```

Soll ein Regelwerk nur gegen eine Teilmenge der Eingabe getestet
werden, erfolgt dies durch Einschränkung des (globalen) Geltungsbereichs
(`scope`) mithilfe eines Filterausdrucks:

```{.toml}
scope = '002@.0 =^ "T"'

[rule.XYZ]
...
````

Nicht bei jeder Regelverletzung handelt es sich gleich um einen Fehler.
Deshalb wird zwischen folgenden Levels unterschieden:

*  _Fehler_ --- `error`,
*  _Warnung_ --- `warning`,
* und _Info_ --- `info`.

Konfiguriert wird das Level über die `level`-Option. Ist die Option
nicht gesetzt, wird automatisch das Level `error` ausgewählt:

```{.toml}
[rule.XYZ]
level = "warning"
````

Zur Nachvollziehbarkeit und Dokumentation kann eine Regel mit einer
Beschreibung (`description`) und einem Link (`link`) ausgezeichnet
werden:

```{.toml}
[rule.XYZ]
description = "Findet Datensätze, die gegen die Regel XYZ verstoßen."
link = "https://www.example.org/XYZ"
````

## Checks


### Datetime

Der `datetime`-Check überprüft, ob in einem Feld ein gültiges Datum bzw.
Zeitangabe steht. Die Angabe der zu überprüfenden Felder erfolgt mittels
der Option `path`, welche einen Pfadausdruck erwartet.

<!-- TODO: Link zu Pfad-Spezifikation setzen. -->

```{.toml}
[rule.DATETIME]
check = "datetime"
description = "Findet ungültige Datumsangaben im Feld 010@ $D."
link = "https://wiki.dnb.de/display/ILTIS/1500"
format = "%Y-%m-%d"
path = "010@.D"
```

Folgende Optionen können zusätzlich gesetzt werden:

`format = <string>`
: Angabe des Format-Strings, der das Format der Datums- bzw. Zeitangabe
festlegt. Ist die Option nicht gesetzt, wird standardmäßig der Format-
String `%Y-%m-%d` verwendet.

`message = <string>`
: Angabe eines Strings, der in die Spalte `message` der Ausgabedatei
geschrieben wird. Der Platzhalter `{}` wird durch den ungültigen Wert
ersetzt.

`offset = <n>`
: Mit der `offset`-Option können die ersten `<n>` Zeichen übersprungen
werden, wenn die Datums- bzw. Zeitangabe nicht am Anfang des zu
überprüfenden Feldes steht.

### Filter

Mittels des `filter`-Checks können Datensätze gefunden werden, die einem
Filterausdruck entsprechen. Zum Beispiel können mit der folgenden Regel
Datensätze gefunden werden, die einen ungültigen Projektcode im Feld
`017C $a` enthalten:

```{.toml}
[rule.TITLE-017C-001]
check = "filter"
description = "Findet ungültige Projektcodes im Feld 017C $a."
link = "https://wiki.dnb.de/display/ILTIS/0602"
filter = '017C.a not in ["a","d","f","i","m","n","t"]'
```

Folgende Optionen können zusätzlich gesetzt werden:

`case-ignore = true | false`
: Ist die Option gesetzt, wird die Groß- und Kleinschreibung beim
Vergleichen von Werten ignoriert.

`strsim-threshold = <value>`
: Festlegen des Schwellenwerts beim Ähnlichkeitsvergleich von
Zeichenketten mittels des `=*`-Operators.

`invert-match = true | false`
: Ist die Option gesetzt, werden Datensätze gefunden, die *nicht* dem
Filterausdruck entsprechen.


### ISNI

Die Gültigkeit eines [ISNI]-Identifikators, bspw. einer [ORCID], lässt
sich mit dem `isni`-Check überprüfen.

Die folgende Regel findet ungültige ORCID-Identifikatoren im Feld `028A
$y`, wobei nur die Werte überprüft werden, die mit dem Prefix `(orcid)`
beginnen:

```{.toml}
[rule.ORCID]
check = 'isni'
description = 'Findet ungültige ORCID-Einträge im Feld 028A $y.'
link = 'https://wiki.dnb.de/display/ILTIS/3000'
path = '028A{ y | y =^ "(orcid)" }'
prefix = '(orcid)'
```

Weitere Optionen:

`case-ignore = true | false`
: Ist die Option gesetzt, wird die Groß- und Kleinschreibung beim
Vergleichen von Werten ignoriert.

`strsim-threshold = <value>`
: Festlegen des Schwellenwerts beim Ähnlichkeitsvergleich von
Zeichenketten mittels des `=*`-Operators.

`prefix = '<prefix>'`
: Es werden nur Werte überprüft, die mit dem Prefix `<prefix>` beginnen.
Wird kein Prefix angegeben, werden alle Werte des `path`-Ausdrucks
überprüft.


### Unicode

Der `unicode`-Check überprüft, ob die Werte aller Unterfelder eines
Datensatzes gültige Unicode-Zeichenketten enthalten.

```{.toml}
[rule.UNICODE]
check = "unicode"
```

Darüber hinaus kann überprüft werden, ob diese Werte in einer der
Unicode-Normalformen `nfc`, `nfkc`, `nfd` oder `nfkd` vorliegen. Ein
gefundener Wert kann über die `message`-Option mit in die Ausgabedatei
geschrieben werden. Der Platzhalter `{}` wird durch den ungültigen Wert
ersetzt:

```{.toml}
[rule.UNICODE]
check = "unicode"
normalization = "nfd"
message = "Ungültiger Wert '{}'!"
```

## Optionen

`-s`, `--skip-invalid`
: Überspringt jene Zeilen aus der Eingabe, die nicht dekodiert werden
konnten.

`-p`, `--progress`
: Anzeige des Fortschritts, der die Anzahl der eingelesenen gültigen
sowie invaliden Datensätze anzeigt. Das Aktivieren der Option erfordert
das Schreiben der Datensätze in eine Datei mittels `-o` bzw. `--output`.

`-R <filename>`, `--rule-set <filename>`
: Angabe eines Regelwerks, gegen das die Datensätze aus der Eingabe
getestet werden.

`-o`, `--output`
: Angabe, in welche Datei die Ausgabe geschrieben werden soll.
Standardmäßig wird die Ausgabe in die Standardausgabe `stdout`
geschrieben.

[ISNI]: https://de.wikipedia.org/wiki/International_Standard_Name_Identifier
[ORCID]: https://de.wikipedia.org/wiki/ORCID
