baseURL = "https://deutsche-nationalbibliothek.github.io/pica-rs/book/"
languageCode = "de-DE"
title = "pica-rs"

enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[params]
BookComments = false
BookSearch = false
BookToc = false
