name: Daily

on:
  schedule:
    - cron: '52 6 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: abbbi/github-actions-tune@v1
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.toml') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            target/
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upgrades:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abbbi/github-actions-tune@v1
      - uses: actions/cache@v2
        with:
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/Cargo.toml') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            target/
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: |
          cargo install -f cargo-upgrades
      - run: |
          cargo upgrades
