name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '52 6 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abbbi/github-actions-tune@v1
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.toml') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upgrades:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abbbi/github-actions-tune@v1
      - uses: actions/cache@v3
        with:
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/Cargo.toml') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - name: "Install `cargo-upgrades`"
        run: |
          cargo install -f cargo-upgrades
      - run: |
          cargo upgrades
