name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '52 6 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: dtolnay/install@cargo-outdated
      - uses: Swatinem/rust-cache@v2
      - run: cargo update
      - run: cargo outdated --workspace --exit-code 1
