name: rust

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '10 10  * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-Dwarnings"
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu-latest, toolchain: stable, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: beta, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: nightly, triple: x86_64-unknown-linux-gnu }
          - { os: windows-latest, toolchain: stable, triple: i686-pc-windows-msvc }
          - { os: macos-latest, toolchain: stable, triple: x86_64-apple-darwin }
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: ${{ matrix.target.toolchain }}
          targets: ${{ matrix.target.triple }}

      - name: Install nextest
        uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
        with:
          tool: nextest

      - name: Run tests
        if: ${{ matrix.target.toolchain != 'nightly' }}
        run: |
          cargo nextest run --workspace -F performant,compat,unstable --profile ci
          cargo test --doc --workspace --features performant,compat,unstable --no-fail-fast

      - name: Run tests (nightly)
        if: ${{ matrix.target.toolchain == 'nightly' }}
        run: |
          cargo nextest run --workspace --all-features --profile ci
          cargo test --doc --workspace --all-features --no-fail-fast

  fuzz:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 900
    strategy:
      matrix:
        item:
          - { name: pica-record-ref, fuzz-dir: fuzz, target: fuzz-record-ref, max-total-time: 120 }
          - { name: pica-record-matcher, fuzz-dir: fuzz, target: fuzz-record-matcher, max-total-time: 200 }
          - { name: pica-path, fuzz-dir: fuzz, target: fuzz-path, max-total-time: 200 }
          - { name: pica-format, fuzz-dir: fuzz, target: fuzz-format, max-total-time: 200 }
          - { name: pica-query, fuzz-dir: fuzz, target: fuzz-query, max-total-time: 200 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        uses: dtolnay/install@d0dc46e85ffd2c174b5ac0489e17f95dae84fa5a # cargo-fuzz
        
      - name: Run cargo-fuzz
        run: |
          cargo fuzz run --fuzz-dir ${{ matrix.item.fuzz-dir }} --jobs 2 ${{ matrix.item.target }} -- -max_total_time=${{ matrix.item.max-total-time }}

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false
            
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          components: clippy
          
      - name: Run clippy
        run: |
          cargo clippy --workspace --all-features

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          components: rustfmt
      - name: Run rustfmt
        run: |
          cargo fmt --all --check

  features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly

      - name: Install cargo-hack
        uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
        with:
          tool: cargo-hack

      - name: Check powerset
        run: |
          cargo hack check --all --feature-powerset --exclude-features serde --no-dev-deps

      - name: Test powerset
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cargo hack test --all --feature-powerset --exclude-features serde

  udeps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          
      - name: Run udeps
        run: |
          cargo install --locked cargo-udeps
          cargo udeps --workspace

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
      - name: Tests docs
        run: |
          cargo doc --no-deps

  deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          arguments: --config .deny.toml --workspace --all-features
          rust-version: stable

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false
            
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: "1.95"

      - name: Check MSRV
        run: |
          cargo check --workspace -F compat,performant,unstable

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0

  cross:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu-latest, toolchain: stable, triple: x86_64-unknown-linux-musl }
          - { os: ubuntu-latest, toolchain: stable, triple: aarch64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: stable, triple: aarch64-unknown-linux-musl }
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false
            
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: ${{ matrix.target.toolchain }}
          targets: ${{ matrix.target.triple }}
          
      - name: Install cross
        run: |
          cargo install cross

      - name: Run cross
        run: |
          cross clean # see https://github.com/cross-rs/cross/issues/724
          cross build --target ${{ matrix.target.triple }}

  careful:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          
      - name: Intall careful
        run: |
          cargo install cargo-careful

      - name: Run careful
        run: |
          cargo careful test --workspace --all-features

  miri:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false
            
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          components: miri

      - name: Install nextest
        uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
        with:
          tool: nextest

      - name: Run miri (nextest)
        env:
          MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-disable-isolation
        run: |
          cargo miri nextest run --workspace --lib -F compat,performant,unstable --profile ci

      - name: Run miri (doctests)
        env:
          MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-disable-isolation
        run: |
          cargo miri test --workspace --doc -F compat,performant,unstable

  audit:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          
      - name: Run cargo update
        run: |
          cargo update

      - name: Run audit
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          ignore: RUSTSEC-2025-0141,RUSTSEC-2026-0195,RUSTSEC-2026-0194
          token: ${{ secrets.GITHUB_TOKEN }}

  conclusion:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - audit
      - careful
      - clippy
      - cross
      - deny
      - features
      - fuzz
      - miri
      - msrv
      - rustdoc
      - rustfmt
      - test
      - udeps
      - zizmor
    steps:
      - name: Check for cancelled jobs
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: |
          exit 1

      - name: Check for failed jobs
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          exit 1

      - name: Finish job
        run: |
          exit 0
